# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "boxcutter/centos66"
    config.vm.provision "shell", path: "ansible-install.sh"

    if Vagrant::Util::Platform.windows?

      config.vm.provision :guest_ansible do |ansible|
        ansible.playbook = "playbooks/env-front-portal_build.yml"
	ansible.verbose = "vvv"
      end

    else

      config.vm.provision :ansible do |ansible|
        ansible.playbook = "playbooks/env-front-portal_build.yml"
      end

    end
end
