---

# Trigger pipelines, we need the first job to be built at least once
# so that we can visualise the full pipeline
#
- name: install python-pip
  yum: name=python-pip
    state=present
  tags:
    - jenkins_pipeline

- name: install httplib2
  pip: name=httplib2
    executable=/usr/bin/pip
    state=present
  tags:
    - jenkins_pipeline

- name: kick first job in the pipeline
  uri: url="http://localhost:8080/job/{{item}}/buildWithParameters"
    follow_redirects=all
    method=GET
    status_code=200,201
  with_items:
    - "{{ azulinho_jenkins_kick_pipeline['pipeline_first_jobs'] }}"
  tags:
    - jenkins_pipeline

