
# goddamn you RH, all your packages from the flinstones era
# grab the latest git from rpmforge-extras
# that repo is disabled by default
- name: Ensure latest git is installed
  yum: name=git
    enablerepo=rpmforge-extras
    state=latest
  tags:
    - latest-git
