USE [Operations]
GO

/****** Object:  Table [dbo].[transactions]    Script Date: 26/05/2016 07:30:14 p.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[transactions](
	[Id] [char](36) NOT NULL,
	[CreateTimestamp] [datetime] NULL,
	[UpdateTimestamp] [datetime] NULL,
	[TransportTimestamp] [datetime] NULL,
	[RequestInputTimestamp] [datetime] NULL,
	[RequestOutputTimestamp] [datetime] NULL,
	[AnswerInputTimestamp] [datetime] NULL,
	[AnswerOutputTimestamp] [datetime] NULL,
	[DeviceIdentification] [varchar](36) NULL,
	[LocationIdentification] [int] NULL,
	[ServiceName] [varchar](128) NULL,
	[OperationName] [varchar](128) NULL,
	[SequenceNumber] [int] NULL,
	[Status] [int] NULL,
	[UserIdentification] [varchar](36) NULL,
	[ProviderIdentification] [varchar](36) NULL,
	[ProviderTransactionID] [varchar](64) NULL,
	[DeviceTransactionID] [varchar](64) NULL,
	[SyncStatus] [int] NULL,
	[SyncTimestamp] [datetime] NULL,
	[ProductIdentification] [int] NULL,
	[RetrievalReferenceNumber] [varchar](45) NULL,
	[FacilitiesPayments] [int] NULL,
	[FacilitiesType] [char](1) NULL,
	[CurrencyCode] [int] NULL,
	[Amount] [decimal](12, 2) NULL,
	[FeeAmount] [decimal](12, 2) NULL,
	[TaxAmount] [decimal](12, 2) NULL,
	[ComissionAmount] [decimal](12, 2) NULL,
	[ServiceChargeAmount] [decimal](12, 2) NULL,
	[MerchantIdentification] [varchar](36) NULL,
	[ProviderDeviceIdentification] [varchar](36) NULL,
	[ReverseStatus] [int] NULL,
	[ReverseTimestamp] [datetime] NULL,
	[VoidStatus] [int] NULL,
	[VoidTimestamp] [datetime] NULL,
	[VoidUserIdentification] [varchar](36) NULL,
	[RefundStatus] [int] NULL,
	[RefundTimestamp] [datetime] NULL,
	[RefundUserIdentification] [varchar](36) NULL,
	[RefundAmount] [decimal](12, 2) NULL,
	[CloseStatus] [int] NULL,
	[CloseTimestamp] [datetime] NULL,
	[CloseUserIdentification] [varchar](36) NULL,
	[SettlementStatus] [int] NULL,
	[SettlementTimestamp] [datetime] NULL,
	[SettlementUserIdentification] [varchar](36) NULL,
	[SettlementAmount] [decimal](12, 2) NULL,
	[SettlementTransactionId] [char](36) NULL,
	[RevisionStatus] [int] NULL,
	[RevisionTimestamp] [datetime] NULL,
	[RevisionReason] [varchar](64) NULL,
	[RevisionSource] [varchar](36) NULL,
	[BatchNumber] [int] NULL,
	[TicketNumber] [int] NULL,
	[ProviderBatchNumber] [int] NULL,
	[ProviderTicketNumber] [int] NULL,
	[ProviderTraceNumber] [bigint] NULL,
	[ProviderAuthorizationCode] [varchar](8) NULL,
	[CustomerIdentification] [varchar](36) NULL,
	[CredentialInputMode] [int] NULL,
	[CredentialMask] [varchar](20) NULL,
	[CredentialEncrypted] [varchar](512) NULL,
	[CredentialExpDate] [int] NULL,
	[CredentialCardHash] [varchar](80) NULL,
	[CredentialHolderName] [varchar](48) NULL,
	[CredentialAddress] [varchar](48) NULL,
	[CredentialDocumentType] [varchar](36) NULL,
	[CredentialDocumentNumber] [varchar](24) NULL,
	[CredentialEmailAddress] [varchar](64) NULL,
	[DeviceFingerprint] [varchar](36) NULL,
	[ResultCode] [int] NULL,
	[ResultMessage] [varchar](255) NULL,
	[ProviderResultCode] [varchar](32) NULL,
	[ProviderResultMessage] [varchar](255) NULL,
	[Channel] [varchar](36) NULL,
	[CaptureAddress] [varchar](45) NULL,
	[CaptureTimestamp] [datetime] NULL,
	[RequestAddress] [varchar](45) NULL,
	[RequestTimestamp] [datetime] NULL,
	[AnswerAddress] [varchar](45) NULL,
	[AnswerTimestamp] [datetime] NULL,
	[RedirectURLOK] [varchar](255) NULL,
	[RedirectURLError] [varchar](255) NULL,
	[CredentialBirthday] [date] NULL,
	[BillHolderName] [varchar](48) NULL,
	[BillHolderDocumentType] [varchar](36) NULL,
	[BillHolderDocumentNumber] [varchar](24) NULL,
	[ProviderCustomerCode] [int] NULL,
	[ProviderCustomerAdditionalCode] [int] NULL,
	[ChargeLatePaymentAmount] [decimal](12, 2) NULL,
	[DifferenceBetweenFirstExpiration] [int] NULL,
	[DaysAfterFirstExpiration] [int] NULL,
	[CouponExpirationDate] [date] NULL,
	[InvoiceExpirationDate] [datetime] NULL,
	[PaymentBarCode] [varchar](128) NULL,
	[InvoiceBarCode] [varchar](128) NULL,
	[LiquidationStatus] [int] NOT NULL CONSTRAINT [DF_Txs_LiquidationStatus]  DEFAULT ((0)),
	[LiquidationTimestamp] [datetime] NULL,
	[ReconciliationStatus] [int] NOT NULL CONSTRAINT [DF_Txs_ReconciliationStatus]  DEFAULT ((0)),
	[ReconciliationTimestamp] [datetime] NULL,
	[AvailableStatus] [int] NOT NULL CONSTRAINT [DF_Txs_AvailableStatus]  DEFAULT ((0)),
	[AvailableTimestamp] [datetime] NULL,
	[AvailableAmount] [decimal](12, 2) NULL,
	[BillingStatus] [int] NOT NULL CONSTRAINT [DF_Txs_BillingStatus]  DEFAULT ((0)),
	[BillingTimestamp] [datetime] NULL,
	[ProcessorResultCode] [varchar](16) NULL,
	[ProcessorResultMessage] [varchar](255) NULL,
	[ButtonId] [int] NULL,
	[ButtonExternalId] [varchar](128) NULL,
	[ButtonMinimumAmount] [decimal](12, 2) NULL,
	[ButtonMaximumAmount] [decimal](12, 2) NULL,
	[SaleConcept] [varchar](255) NULL,
	[MerchantActivityCode] [int] NULL,
	[ChargebackStatus] [int] NULL,
	[ChargebackTimestamp] [datetime] NULL,
	[ChargebackReason] [varchar](64) NULL,
	[CashoutStatus] [int] NOT NULL CONSTRAINT [DF_Txs_CashoutStatus]  DEFAULT ((0)),
	[CashoutTimestamp] [datetime] NULL,
	[FilingDeadline] [datetime] NULL,
	[PaymentDeadline] [datetime] NULL,
	[PaymentTimestamp] [datetime] NULL,
	[PaymentStatus] [int] NULL,
	[CouponStatus] [varchar](50) NULL,
	[CouponDaysBetweenExpDates] [int] NULL,
	[CouponValidityDays] [int] NULL,
	[CouponFee] [decimal](18, 0) NULL,
	[CouponSecondExpirationDate] [date] NULL,
	[CouponClientCode] [varchar](32) NULL,
	[CouponSubscriber] [varchar](128) NULL,
	[CouponOperationId] [varchar](64) NULL,
	[OriginalOperationId] [char](36) NULL,
	[TransactionStatus] [varchar](20) NULL,
	[ProductType] [int] NULL,
	[BankIdentification] [int] NULL,
	[BuyerAccountIdentification] [int] NULL,
	[PrivateRequestKey] [varchar](48) NULL,
	[PublicRequestKey] [varchar](48) NULL,
	[PrivateAnswerKey] [varchar](48) NULL,
	[PublicAnswerKey] [varchar](48) NULL,
	[PublicIdentification] [decimal](9, 0) NULL,
	[id_medio_pago_cuenta] [int] NULL,
	[AmountBuyer] [decimal](12, 2) NULL,
	[FeeAmountBuyer] [decimal](12, 2) NULL,
	[TaxAmountBuyer] [decimal](12, 2) NULL,
	[PromotionIdentification] [int] NULL,
	[AdditionalData] [xml] NULL,
	[FraudResultCode] [varchar](16) NULL,
	[FraudTransactionID] [varchar](64) NULL,
	[PresentationTimestamp] [datetime] NULL,
	[DocumentationTimestamp] [datetime] NULL,
	[DocumentationURL] [varchar](256) NULL,
	[PushNotifyMethod] [varchar](64) NULL,
	[PushNotifyEndpoint] [varchar](256) NULL,
	[PushNotifyStates] [varchar](256) NULL,
	[PushNotifySentTimestamp] [datetime] NULL,
	[PushNotifyCounter] [int] NULL,
	[Version] [varchar](10) NULL,
	[BuyerIP] [varchar](15) NULL,
	[SDK] [varchar](255) NULL,
	[SDKVersion] [varchar](255) NULL,
	[LenguageVersion] [varchar](255) NULL,
	[PluginVersion] [varchar](255) NULL,
	[ECommerceName] [varchar](255) NULL,
	[ECommerceVersion] [varchar](255) NULL,
	[CMSVersion] [varchar](255) NULL,
	[flag_formulario_cargado] [bit] NOT NULL DEFAULT ((0)),
	[CashoutReleaseStatus] [int] NULL,
	[CashoutReleaseTimestamp] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


